pipelines:
  default:
      - step:
          runs-on:
            - self.hosted
            - linux
            - newrahmat
          script:
            - curl ifconfig.co > ip.pub
            - cat ip.pub
            - whoami
            - pwd