{{- if .Values.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    project: {{ .Values.project }}
    role: {{ .Values.type }}
    env: {{ .Values.env }}

spec:
  # recommenders field can be unset when using the default recommender.
  # When using an alternative recommender, the alternative recommender's name
  # can be specified as the following in a list.
  # recommenders:
  #   - name: 'alternative'
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Values.name }}
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: {{ .Values.MinAllowedCpu }}
          memory: {{ .Values.MinAllowedMemory }}
        maxAllowed:
          cpu: {{ .Values.MaxAllowedCpu }}
          memory: {{ .Values.MaxAllowedMemory }}
        controlledResources: ["cpu", "memory"]
{{- end }}
